/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const CreateGroupArgs = IDL.Record({
  'creator' : IDL.Principal,
  'adminIds' : IDL.Vec(IDL.Principal),
  'name' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'coverImage' : IDL.Opt(ExternalBlob),
});
export const MediaContent = IDL.Record({
  'video' : IDL.Opt(ExternalBlob),
  'text' : IDL.Opt(IDL.Text),
  'image' : IDL.Opt(ExternalBlob),
});
export const PostType = IDL.Variant({
  'regular' : IDL.Null,
  'newsFeed' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'profilePhoto' : IDL.Opt(ExternalBlob),
  'badges' : IDL.Vec(IDL.Text),
  'civicTokenBalance' : IDL.Nat,
  'verifiedStatus' : IDL.Bool,
  'followerCount' : IDL.Nat,
  'location' : IDL.Text,
});
export const Group = IDL.Record({
  'id' : IDL.Nat,
  'creator' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'coverImage' : IDL.Opt(ExternalBlob),
});
export const Page = IDL.Record({
  'owner' : IDL.Principal,
  'profileImage' : IDL.Opt(ExternalBlob),
  'pageName' : IDL.Text,
  'description' : IDL.Text,
  'creationTime' : Time,
  'isPrivate' : IDL.Bool,
  'category' : IDL.Text,
});
export const Poll = IDL.Record({
  'id' : IDL.Nat,
  'creator' : IDL.Principal,
  'question' : IDL.Text,
  'votes' : IDL.Vec(IDL.Nat),
  'isPublic' : IDL.Bool,
  'options' : IDL.Vec(IDL.Text),
});
export const PostEdit = IDL.Record({
  'content' : MediaContent,
  'timestamp' : Time,
});
export const Post = IDL.Record({
  'id' : IDL.Nat,
  'postType' : PostType,
  'seriousLikeCount' : IDL.Nat,
  'likeCount' : IDL.Nat,
  'content' : MediaContent,
  'author' : IDL.Principal,
  'groupId' : IDL.Opt(IDL.Nat),
  'isEdited' : IDL.Bool,
  'editHistory' : IDL.Vec(PostEdit),
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createGroup' : IDL.Func([CreateGroupArgs], [IDL.Nat], []),
  'createPage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob), IDL.Bool],
      [IDL.Nat],
      [],
    ),
  'createPoll' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Text), IDL.Bool],
      [IDL.Nat],
      [],
    ),
  'createPost' : IDL.Func(
      [MediaContent, IDL.Opt(IDL.Nat), PostType],
      [IDL.Nat],
      [],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGroup' : IDL.Func([IDL.Nat], [IDL.Opt(Group)], ['query']),
  'getPage' : IDL.Func([IDL.Nat], [IDL.Opt(Page)], ['query']),
  'getPoll' : IDL.Func([IDL.Nat], [IDL.Opt(Poll)], ['query']),
  'getPost' : IDL.Func([IDL.Nat], [IDL.Opt(Post)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const CreateGroupArgs = IDL.Record({
    'creator' : IDL.Principal,
    'adminIds' : IDL.Vec(IDL.Principal),
    'name' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'coverImage' : IDL.Opt(ExternalBlob),
  });
  const MediaContent = IDL.Record({
    'video' : IDL.Opt(ExternalBlob),
    'text' : IDL.Opt(IDL.Text),
    'image' : IDL.Opt(ExternalBlob),
  });
  const PostType = IDL.Variant({ 'regular' : IDL.Null, 'newsFeed' : IDL.Null });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'profilePhoto' : IDL.Opt(ExternalBlob),
    'badges' : IDL.Vec(IDL.Text),
    'civicTokenBalance' : IDL.Nat,
    'verifiedStatus' : IDL.Bool,
    'followerCount' : IDL.Nat,
    'location' : IDL.Text,
  });
  const Group = IDL.Record({
    'id' : IDL.Nat,
    'creator' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'coverImage' : IDL.Opt(ExternalBlob),
  });
  const Page = IDL.Record({
    'owner' : IDL.Principal,
    'profileImage' : IDL.Opt(ExternalBlob),
    'pageName' : IDL.Text,
    'description' : IDL.Text,
    'creationTime' : Time,
    'isPrivate' : IDL.Bool,
    'category' : IDL.Text,
  });
  const Poll = IDL.Record({
    'id' : IDL.Nat,
    'creator' : IDL.Principal,
    'question' : IDL.Text,
    'votes' : IDL.Vec(IDL.Nat),
    'isPublic' : IDL.Bool,
    'options' : IDL.Vec(IDL.Text),
  });
  const PostEdit = IDL.Record({ 'content' : MediaContent, 'timestamp' : Time });
  const Post = IDL.Record({
    'id' : IDL.Nat,
    'postType' : PostType,
    'seriousLikeCount' : IDL.Nat,
    'likeCount' : IDL.Nat,
    'content' : MediaContent,
    'author' : IDL.Principal,
    'groupId' : IDL.Opt(IDL.Nat),
    'isEdited' : IDL.Bool,
    'editHistory' : IDL.Vec(PostEdit),
    'timestamp' : Time,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createGroup' : IDL.Func([CreateGroupArgs], [IDL.Nat], []),
    'createPage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob), IDL.Bool],
        [IDL.Nat],
        [],
      ),
    'createPoll' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Text), IDL.Bool],
        [IDL.Nat],
        [],
      ),
    'createPost' : IDL.Func(
        [MediaContent, IDL.Opt(IDL.Nat), PostType],
        [IDL.Nat],
        [],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGroup' : IDL.Func([IDL.Nat], [IDL.Opt(Group)], ['query']),
    'getPage' : IDL.Func([IDL.Nat], [IDL.Opt(Page)], ['query']),
    'getPoll' : IDL.Func([IDL.Nat], [IDL.Opt(Poll)], ['query']),
    'getPost' : IDL.Func([IDL.Nat], [IDL.Opt(Post)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };