/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const MediaContent = IDL.Record({
  'video' : IDL.Opt(ExternalBlob),
  'text' : IDL.Opt(IDL.Text),
  'image' : IDL.Opt(ExternalBlob),
});
export const PostType = IDL.Variant({
  'regular' : IDL.Null,
  'newsFeed' : IDL.Null,
});
export const Time = IDL.Int;
export const Post = IDL.Record({
  'id' : IDL.Nat,
  'postType' : PostType,
  'seriousLikeCount' : IDL.Nat,
  'likeCount' : IDL.Nat,
  'content' : MediaContent,
  'author' : IDL.Principal,
  'groupId' : IDL.Opt(IDL.Nat),
  'timestamp' : Time,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'profilePhoto' : IDL.Opt(ExternalBlob),
  'badges' : IDL.Vec(IDL.Text),
  'verifiedStatus' : IDL.Bool,
  'followerCount' : IDL.Nat,
  'location' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createNewsFeedPost' : IDL.Func([MediaContent], [IDL.Nat], []),
  'createPost' : IDL.Func([MediaContent, IDL.Opt(IDL.Nat)], [IDL.Nat], []),
  'deletePost' : IDL.Func([IDL.Nat], [], []),
  'getAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCountries' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getDistrictsByState' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
  'getNewsFeedPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getStatesByCountry' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
  'getUserPosts' : IDL.Func([IDL.Principal], [IDL.Vec(Post)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const MediaContent = IDL.Record({
    'video' : IDL.Opt(ExternalBlob),
    'text' : IDL.Opt(IDL.Text),
    'image' : IDL.Opt(ExternalBlob),
  });
  const PostType = IDL.Variant({ 'regular' : IDL.Null, 'newsFeed' : IDL.Null });
  const Time = IDL.Int;
  const Post = IDL.Record({
    'id' : IDL.Nat,
    'postType' : PostType,
    'seriousLikeCount' : IDL.Nat,
    'likeCount' : IDL.Nat,
    'content' : MediaContent,
    'author' : IDL.Principal,
    'groupId' : IDL.Opt(IDL.Nat),
    'timestamp' : Time,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'profilePhoto' : IDL.Opt(ExternalBlob),
    'badges' : IDL.Vec(IDL.Text),
    'verifiedStatus' : IDL.Bool,
    'followerCount' : IDL.Nat,
    'location' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createNewsFeedPost' : IDL.Func([MediaContent], [IDL.Nat], []),
    'createPost' : IDL.Func([MediaContent, IDL.Opt(IDL.Nat)], [IDL.Nat], []),
    'deletePost' : IDL.Func([IDL.Nat], [], []),
    'getAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCountries' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getDistrictsByState' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getNewsFeedPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getStatesByCountry' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
    'getUserPosts' : IDL.Func([IDL.Principal], [IDL.Vec(Post)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };